#!/usr/bin/env python3
"""Interactive 3D replay of recorded actions, not live training or control."""
import argparse
import json
from pathlib import Path
from queue import SimpleQueue
import time

import mujoco
from mujoco import viewer as mjviewer
import numpy as np

from twin_sim.regrasp_rl import RegraspRLEnv


def prepare(path):
    report = json.loads(path.read_text())
    seed = report['seed']
    env = RegraspRLEnv(support_repeats=3)
    env.reset(seed=seed, options={'shape_seed': seed})
    skill = env.skill
    frames = []

    def capture():
        return skill.data.qpos.copy(), skill.data.qvel.copy(), skill.status().copy()

    initial = capture()
    frames.extend([initial]*80)
    for row in report['steps']:
        _, _, terminated, truncated, _ = env.step(np.asarray(row['action']))
        frames.append(capture())
        if terminated or truncated:
            break
    if skill.completed != 3 or skill.wrist_retreats != 9:
        raise RuntimeError(f'Replay verification failed for seed {seed}: {skill.status()}')
    if abs(skill.max_drift*1000-report['result']['max_drift_mm']) > .01:
        raise RuntimeError(f'Recorded rollout differs from replay for seed {seed}')
    for _ in range(100):
        skill.step()
        frames.append(capture())
    print(f'Prepared seed {seed}: {len(frames)} frames, verified 9 wrist / 3 fingertip moves', flush=True)
    return skill.model, frames


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path('local/outputs/potato/regrasp_nine'))
    parser.add_argument('--seeds', type=int, nargs='+', default=[100, 101, 102])
    args = parser.parse_args()
    clips = [prepare(args.output/f'seed_{seed}.json') for seed in args.seeds]
    queue = SimpleQueue()
    selected, frame, paused = 0, 0, False
    camera = None
    while True:
        model, frames = clips[selected]
        data = mujoco.MjData(model)
        next_clip = None
        with mjviewer.launch_passive(model, data, key_callback=queue.put) as view:
            if camera is None:
                view.cam.lookat[:] = [.43, 0, .30]
                view.cam.distance, view.cam.azimuth, view.cam.elevation = .43, 135, -22
            else:
                view.cam.lookat[:] = camera[0]
                view.cam.distance, view.cam.azimuth, view.cam.elevation = camera[1:]
            while view.is_running():
                start = time.monotonic()
                while not queue.empty():
                    key = queue.get()
                    if key == 32:
                        paused = not paused
                    elif key == ord('R'):
                        frame = 0
                    elif ord('1') <= key < ord('1')+len(clips):
                        next_clip = key-ord('1')
                if next_clip is not None:
                    camera = (view.cam.lookat.copy(), view.cam.distance, view.cam.azimuth, view.cam.elevation)
                    break
                qpos, qvel, status = frames[frame]
                # Assigning state is ONLY for explicit playback. These frames
                # were generated by mj_step; this is not a physics controller.
                with view.lock():
                    data.qpos[:] = qpos
                    data.qvel[:] = qvel
                    mujoco.mj_forward(model, data)
                view.set_texts([(mujoco.mjtFontScale.mjFONTSCALE_150, mujoco.mjtGridPos.mjGRID_TOPLEFT,
                                '3D PHYSICS REPLAY | PPO + scripted 3x3',
                                f"Sample {selected+1}/{len(clips)} | {status['phase']}\nWrist {status['wrist_retreats']}/9 | Fingers {status['completed']}/3\nSpace: pause | R: replay | 1/2/3: sample\nMouse: rotate / pan / zoom")])
                view.sync()
                if not paused:
                    frame = (frame+1) % len(frames)
                time.sleep(max(0, .02-(time.monotonic()-start)))
        if next_clip is None:
            break
        selected, frame = next_clip, 0


if __name__ == '__main__':
    main()
